# Generated by Django 6.0.3 on 2026-04-26 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='stock',
        ),
    ]
