# Generated by Django 6.0.2 on 2026-02-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options_alter_category_slug'),
        ('store', '0003_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
