# Generated by Django 6.0.3 on 2026-06-25 08:22

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, help_text='Token-based referral URL: /register/?ref=<token>', unique=True)),
                ('referee_discount', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='₹ discount new user gets on first order', max_digits=5)),
                ('referrer_reward', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='₹ wallet credit given to referrer when referee places first order', max_digits=5)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_given', models.BooleanField(default=False, help_text='True after referee places first order')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('referee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='used_referral', to=settings.AUTH_USER_MODEL)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='referral.referralcode')),
            ],
        ),
    ]
