# Generated by Django 6.0.2 on 2026-02-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='account',
            name='reset_token_created_at',
        ),
        migrations.AddField(
            model_name='account',
            name='otp_purpose',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
