# Generated by Django 6.0.2 on 2026-02-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='id_admin',
            new_name='is_admin',
        ),
    ]
