# Generated by Django 6.0.3 on 2026-06-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='otp_purpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
