# Generated by Django 6.0.3 on 2026-04-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_status_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_offer_applicable',
            field=models.BooleanField(default=True),
        ),
    ]
