# Generated by Django 6.0.3 on 2026-04-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_is_offer_applicable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_offer_applicable',
            field=models.BooleanField(default=True, help_text='Uncheck for Men / Women / Kids — allow only for product-type categories.'),
        ),
    ]
