# Generated by Django 6.0.3 on 2026-06-12 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20260420_1454'),
        ('offers', '0002_alter_productoffer_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='category.category'),
        ),
    ]
