# Generated by Django 6.0.3 on 2026-06-18 18:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_categoryoffer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='referee_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='₹ discount new user gets on first order', max_digits=5),
        ),
    ]
