# Generated by Django 6.0.3 on 2026-06-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_referralcode_referee_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referraluse',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='referraluse',
            name='referee',
        ),
        migrations.DeleteModel(
            name='ReferralCode',
        ),
        migrations.DeleteModel(
            name='ReferralUse',
        ),
    ]
