# Generated by Django 6.0.3 on 2026-04-16 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=5, help_text='Alert when stock falls at or below this number')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='store.productvariant')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
                'ordering': ['variant__product__product_name', 'variant__color_name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('add', 'Stock Added'), ('deduct', 'Stock Deducted'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('quantity_changed', models.IntegerField(help_text='Units added or removed (always positive)')),
                ('quantity_after', models.IntegerField(help_text='Stock level after this change')),
                ('reason', models.CharField(choices=[('restock', 'Restock / New Delivery'), ('order', 'Order Placed'), ('order_cancel', 'Order Cancelled / Returned'), ('correction', 'Stock Correction'), ('damage', 'Damaged / Lost'), ('other', 'Other')], max_length=50)),
                ('note', models.TextField(blank=True, help_text='Optional extra detail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.inventory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Log',
                'verbose_name_plural': 'Inventory Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
