# Generated by Django 6.0.3 on 2026-04-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='quantity',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='inventorylog',
            old_name='quantity_after',
            new_name='stock_after',
        ),
        migrations.RenameField(
            model_name='inventorylog',
            old_name='quantity_changed',
            new_name='stock_changed',
        ),
    ]
