# Generated by Django 6.0.3 on 2026-04-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_quantity_inventory_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='stock',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='inventorylog',
            old_name='stock_after',
            new_name='quantity_after',
        ),
        migrations.RenameField(
            model_name='inventorylog',
            old_name='stock_changed',
            new_name='quantity_changed',
        ),
    ]
