# Generated by Django 6.0.3 on 2026-04-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon_order_cancel_reason_order_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='cancelled_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='item_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled'), ('Return Requested', 'Return Requested'), ('Returned', 'Returned')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='return_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='returned_qty',
            field=models.IntegerField(default=0),
        ),
    ]
