# Generated by Django 6.0.3 on 2026-07-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_coupon_remove_couponusage_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='pending_return_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
