# Generated by Django 6.0.3 on 2026-07-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderproduct_pending_return_qty_alter_order_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount',
            new_name='coupon_discount',
        ),
        migrations.AddField(
            model_name='order',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='referral_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='wallet_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
